server:
  port: 8810
spring:
  application:
    name: product-catelog-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/product
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
